[project]
name = "gharchive-streamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rifatcanuzunok", email = "rifatcanuzunok@gmail.com" }
]
requires-python = ">=3.14.6"
dependencies = [
    "debugpy>=1.8.21",
    "pytest>=9.1.1",
    "requests>=2.34.2",
]

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"
